In [ ]:
# This program creates dataset with PCI for all years and products
# Source: https://oec.world/en/rankings/pci/hs4/hs92

# Loading packages

In [ ]:
import pandas as pd
import os
from google.colab import drive

# Setting the ambience

In [ ]:
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [ ]:
work_dir                      = '/content/gdrive/My Drive/ip_complexity/oec_data/create_dataset_complexity'
output_dir                    = '/content/gdrive/My Drive/ip_complexity/oec_data/create_dataset_complexity/output'
download_relatedness_data_dir = '/content/gdrive/My Drive/ip_complexity/oec_data/download_relatedness_data/output/data'

# Oppening datasets

In [ ]:
df_pci_pj = pd.read_csv(work_dir + '/input/OEC_pci_hs4_hs92.csv', sep = ";") # pci at level product p during the year j

# Cleaning

In [ ]:
# Convert to long format using 'HS4 ID' as the identifier variable
df_pci_pj = pd.melt(df_pci_pj, id_vars=['HS4', 'HS4 ID'], var_name='year', value_name='pci')

In [ ]:
df_pci_pj = df_pci_pj.sort_values(by=["HS4","year"])

In [ ]:
df_pci_pj = df_pci_pj.rename(columns = {"HS4": "product_name_hs4", "HS4 ID": "hs4_id"})

# Saving

In [ ]:
df_pci_pj["year"] = df_pci_pj["year"].astype(int)

In [ ]:
df_pci_pj.to_csv(output_dir + '/data/complexity_dataset.csv', index = False)

In [ ]:
df_pci_pj.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 28674 entries, 623 to 28394
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   product_name_hs4  28674 non-null  object
 1   hs4_id            28674 non-null  int64
 2   year              28674 non-null  int64
 3   pci               25915 non-null  float64
dtypes: float64(1), int64(2), object(1)
memory usage: 1.1+ MB

In [ ]:
df_pci_pj.describe()

             hs4_id          year           pci
count  28674.000000  28674.000000  2.591500e+04
mean    5342.118644   2008.000000  6.984381e-13
std     2796.296138      7.789017  9.994982e-01
min      101.000000   1995.000000 -3.568408e+00
25%     2846.000000   2001.000000 -7.496923e-01
50%     5509.500000   2008.000000  8.593600e-02
75%     8211.000000   2015.000000  7.773469e-01
max     9706.000000   2021.000000  3.153356e+00